<a href="https://colab.research.google.com/github/GuoZhuyin/zhuyinasia/blob/main/ArtificialIntelligence/AIprograme_CNN_0528.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from keras.datasets import mnist

In [ ]:
from google.colab import drive

In [ ]:
import os
drive.mount('/content/gdrive',force_remount=True)
os.chdir("/content/gdrive/MyDrive/亞洲大學/大二/人工智慧概論")

Mounted at /content/gdrive


In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

啟用函數

In [ ]:
x_train.shape

(60000, 28, 28)

資料大小

In [ ]:
x_train=x_train.reshape(-1,28,28,1)
x_train.shape

(60000, 28, 28, 1)

In [ ]:
x_test=x_train.reshape(-1,28,28,1)
x_test.shape

(60000, 28, 28, 1)

In [ ]:
y_train[87]

9

確認x,y資料

In [ ]:
y_test[87]

3

In [ ]:
from keras.utils.np_utils import to_categorical

In [ ]:
y_train=to_categorical(y_train)

類別向量轉換為二進位（只有0和1）

One hot encoding

若y_train為7資料格式為(0,0,0,0,0,0,1,0,0)

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [ ]:
y_train.shape

(60000, 10)

In [ ]:
y_train[87]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

//建立卷積神經網路(CNN)

In [ ]:
from keras.models import Sequential
#from keras import models
#network=models.Sequential
from keras import layers

In [ ]:
network=Sequential()
network.add(layers.Conv2D(32,(3,3),padding='same',activation='relu',input_shape=(28,28,1)))#捲積層
network.add(layers.MaxPooling2D((2,2))) #最大池化
network.add(layers.Conv2D(64,(3,3),padding='same',activation='relu'))
network.add(layers.MaxPooling2D((2,2)))

In [ ]:
network.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 14, 14, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 7, 7, 64)          0         
Total params: 18,816
Trainable params: 18,816
Non-trainable params: 0
_________________________________________________________________


In [ ]:
network.add(layers.Flatten())#

In [ ]:
network.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

編譯給機器看(損失函數,優化函數,數值指標)

In [ ]:
network.add(layers.Dense(512,activation='relu'))
network.add(layers.Dense(256,activation='relu'))
network.add(layers.Dense(10,activation='softmax'))

In [ ]:
network.fit(x_train,y_train,epochs=5,batch_size=128)
#network.fit(x_train.reshape,y_train,epochs局,切片)

Epoch 1/5
469/469 [==============================] - 79s 167ms/step - loss: 2.1376 - accuracy: 0.8456
Epoch 2/5
469/469 [==============================] - 78s 167ms/step - loss: 0.0416 - accuracy: 0.9870
Epoch 3/5
469/469 [==============================] - 78s 166ms/step - loss: 0.0249 - accuracy: 0.9913
Epoch 4/5
469/469 [==============================] - 77s 165ms/step - loss: 0.0196 - accuracy: 0.9929
Epoch 5/5
469/469 [==============================] - 78s 165ms/step - loss: 0.0185 - accuracy: 0.9934


切片*469大約等於y_train()60000筆資料

In [ ]:
predict=network.predict_classes(x_test)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
predict[87] #y_test[87]

9

In [ ]:
predict[1500]

9

In [ ]:
y_test[1500]

7

In [ ]:
np.nonzero(predict!=y_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


(array([0]),)

In [ ]:
np.count_nonzero(predict!=y_test)/len(y_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


0.0001

錯誤率，預測值錯誤個數/所有y_test個數