<a href="https://colab.research.google.com/github/GuoZhuyin/zhuyinasia/blob/main/ArtificialIntelligence/AIprograme_Transferlearning_0618.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from keras.datasets import mnist

In [ ]:
from google.colab import drive

In [ ]:
import os
drive.mount('/content/gdrive',force_remount=True)
os.chdir("/content/gdrive/MyDrive/亞洲大學/大二/人工智慧概論")

Mounted at /content/gdrive


In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

啟用函數

In [ ]:
#Python教學
y_train==1

array([False, False, False, ..., False, False, False])

In [ ]:
aaa=x_train[y_train==1]
aaa.shape

(6742, 28, 28)

In [ ]:
bbb=x_train[y_train==2]
bbb.shape

(5958, 28, 28)

In [ ]:
a=np.array([1,0,1,1])
b=np.array([0,0,1,0])
a,b

(array([1, 0, 1, 1]), array([0, 0, 1, 0]))

In [ ]:
a|b

array([1, 0, 1, 1])

In [ ]:
a&b
#Python教學

array([0, 0, 1, 0])

In [ ]:
x_train_small=x_train[(y_train==1) | (y_train==2)]
y_train_small=y_train[(y_train==1) | (y_train==2)]
x_train_big=x_train[(y_train!=1) & (y_train!=2)]
y_train_big=y_train[(y_train!=1) & (y_train!=2)]

In [ ]:
x_train_small.shape,y_train_small.shape

((12700, 28, 28), (12700,))

In [ ]:
x_train_big.shape,y_train_big.shape

((47300, 28, 28), (47300,))

In [ ]:
from keras.utils.np_utils import to_categorical

In [ ]:
y_train=to_categorical(y_train)

類別向量轉換為二進位（只有0和1）

one hot encoding

若y_train為7資料格式為(0,0,0,0,0,0,1,0,0)

In [ ]:
y_train.shape

(60000, 10)

In [ ]:
from keras.models import Sequential
#from keras import models
#network=models.Sequential
from keras import layers

In [ ]:
network=Sequential()

In [ ]:
network.add(layers.Dense(1024,activation='relu',input_shape=(28*28,))) #layers(類神經網路節點,激勵函數,丟入像素)
network.add(layers.Dense(512,activation='relu'))
network.add(layers.Dense(256,activation='relu'))
network.add(layers.Dense(10,activation='softmax'))

In [ ]:
network.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

編譯給機器看(損失函數,優化函數,數值指標)

In [ ]:
network.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 1024)              803840    
_________________________________________________________________
dense_5 (Dense)              (None, 512)               524800    
_________________________________________________________________
dense_6 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_7 (Dense)              (None, 10)                2570      
Total params: 1,462,538
Trainable params: 1,462,538
Non-trainable params: 0
_________________________________________________________________


In [ ]:
network.fit(x_train.reshape(-1,28*28),y_train,epochs=5,batch_size=128)
#network.fit(x_train.reshape,y_train,epochs局,切片)

Epoch 1/5
469/469 [==============================] - 13s 25ms/step - loss: 8.3052 - accuracy: 0.8222
Epoch 2/5
469/469 [==============================] - 12s 25ms/step - loss: 0.1403 - accuracy: 0.9622
Epoch 3/5
469/469 [==============================] - 12s 25ms/step - loss: 0.0883 - accuracy: 0.9757
Epoch 4/5
469/469 [==============================] - 12s 26ms/step - loss: 0.0673 - accuracy: 0.9797
Epoch 5/5
469/469 [==============================] - 12s 26ms/step - loss: 0.0713 - accuracy: 0.9792


切片*469大約等於y_train()60000筆資料